/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 3.5 */
/* Sun Mar 29 16:12:04 2020 */

/* parameterized module instance */
NCOAdder __ (.DataA( ), .DataB( ), .Clock( ), .Reset( ), .Result( ));
