/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Fri Jan 24 21:01:21 2020 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
