/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n TestFifo -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 64 -width 256 -rwidth 256 -no_enable -pe 10 -pf 40  */
/* Fri Nov 23 10:26:54 2018 */


`timescale 1 ns / 1 ps
module TestFifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [255:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [255:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    defparam TestFifo_0_14.FULLPOINTER1 = "0b00001111110000" ;
    defparam TestFifo_0_14.FULLPOINTER = "0b00010000000000" ;
    defparam TestFifo_0_14.AFPOINTER1 = "0b00001001110000" ;
    defparam TestFifo_0_14.AFPOINTER = "0b00001010000000" ;
    defparam TestFifo_0_14.AEPOINTER1 = "0b00000010110000" ;
    defparam TestFifo_0_14.AEPOINTER = "0b00000010100000" ;
    defparam TestFifo_0_14.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_0_14.GSR = "DISABLED" ;
    defparam TestFifo_0_14.RESETMODE = "ASYNC" ;
    defparam TestFifo_0_14.REGMODE = "NOREG" ;
    defparam TestFifo_0_14.CSDECODE_R = "0b11" ;
    defparam TestFifo_0_14.CSDECODE_W = "0b11" ;
    defparam TestFifo_0_14.DATA_WIDTH_R = 18 ;
    defparam TestFifo_0_14.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_0_14 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(Data[16]), .DI17(Data[17]), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[9]), .DO1(Q[10]), .DO2(Q[11]), 
        .DO3(Q[12]), .DO4(Q[13]), .DO5(Q[14]), .DO6(Q[15]), .DO7(Q[16]), 
        .DO8(Q[17]), .DO9(Q[0]), .DO10(Q[1]), .DO11(Q[2]), .DO12(Q[3]), 
        .DO13(Q[4]), .DO14(Q[5]), .DO15(Q[6]), .DO16(Q[7]), .DO17(Q[8]), 
        .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    defparam TestFifo_1_13.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_1_13.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_1_13.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_1_13.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_1_13.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_1_13.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_1_13.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_1_13.GSR = "DISABLED" ;
    defparam TestFifo_1_13.RESETMODE = "ASYNC" ;
    defparam TestFifo_1_13.REGMODE = "NOREG" ;
    defparam TestFifo_1_13.CSDECODE_R = "0b11" ;
    defparam TestFifo_1_13.CSDECODE_W = "0b11" ;
    defparam TestFifo_1_13.DATA_WIDTH_R = 18 ;
    defparam TestFifo_1_13.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_1_13 (.DI0(Data[18]), .DI1(Data[19]), .DI2(Data[20]), 
        .DI3(Data[21]), .DI4(Data[22]), .DI5(Data[23]), .DI6(Data[24]), 
        .DI7(Data[25]), .DI8(Data[26]), .DI9(Data[27]), .DI10(Data[28]), 
        .DI11(Data[29]), .DI12(Data[30]), .DI13(Data[31]), .DI14(Data[32]), 
        .DI15(Data[33]), .DI16(Data[34]), .DI17(Data[35]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[27]), .DO1(Q[28]), 
        .DO2(Q[29]), .DO3(Q[30]), .DO4(Q[31]), .DO5(Q[32]), .DO6(Q[33]), 
        .DO7(Q[34]), .DO8(Q[35]), .DO9(Q[18]), .DO10(Q[19]), .DO11(Q[20]), 
        .DO12(Q[21]), .DO13(Q[22]), .DO14(Q[23]), .DO15(Q[24]), .DO16(Q[25]), 
        .DO17(Q[26]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_2_12.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_2_12.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_2_12.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_2_12.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_2_12.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_2_12.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_2_12.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_2_12.GSR = "DISABLED" ;
    defparam TestFifo_2_12.RESETMODE = "ASYNC" ;
    defparam TestFifo_2_12.REGMODE = "NOREG" ;
    defparam TestFifo_2_12.CSDECODE_R = "0b11" ;
    defparam TestFifo_2_12.CSDECODE_W = "0b11" ;
    defparam TestFifo_2_12.DATA_WIDTH_R = 18 ;
    defparam TestFifo_2_12.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_2_12 (.DI0(Data[36]), .DI1(Data[37]), .DI2(Data[38]), 
        .DI3(Data[39]), .DI4(Data[40]), .DI5(Data[41]), .DI6(Data[42]), 
        .DI7(Data[43]), .DI8(Data[44]), .DI9(Data[45]), .DI10(Data[46]), 
        .DI11(Data[47]), .DI12(Data[48]), .DI13(Data[49]), .DI14(Data[50]), 
        .DI15(Data[51]), .DI16(Data[52]), .DI17(Data[53]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[45]), .DO1(Q[46]), 
        .DO2(Q[47]), .DO3(Q[48]), .DO4(Q[49]), .DO5(Q[50]), .DO6(Q[51]), 
        .DO7(Q[52]), .DO8(Q[53]), .DO9(Q[36]), .DO10(Q[37]), .DO11(Q[38]), 
        .DO12(Q[39]), .DO13(Q[40]), .DO14(Q[41]), .DO15(Q[42]), .DO16(Q[43]), 
        .DO17(Q[44]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_3_11.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_3_11.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_3_11.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_3_11.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_3_11.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_3_11.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_3_11.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_3_11.GSR = "DISABLED" ;
    defparam TestFifo_3_11.RESETMODE = "ASYNC" ;
    defparam TestFifo_3_11.REGMODE = "NOREG" ;
    defparam TestFifo_3_11.CSDECODE_R = "0b11" ;
    defparam TestFifo_3_11.CSDECODE_W = "0b11" ;
    defparam TestFifo_3_11.DATA_WIDTH_R = 18 ;
    defparam TestFifo_3_11.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_3_11 (.DI0(Data[54]), .DI1(Data[55]), .DI2(Data[56]), 
        .DI3(Data[57]), .DI4(Data[58]), .DI5(Data[59]), .DI6(Data[60]), 
        .DI7(Data[61]), .DI8(Data[62]), .DI9(Data[63]), .DI10(Data[64]), 
        .DI11(Data[65]), .DI12(Data[66]), .DI13(Data[67]), .DI14(Data[68]), 
        .DI15(Data[69]), .DI16(Data[70]), .DI17(Data[71]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[63]), .DO1(Q[64]), 
        .DO2(Q[65]), .DO3(Q[66]), .DO4(Q[67]), .DO5(Q[68]), .DO6(Q[69]), 
        .DO7(Q[70]), .DO8(Q[71]), .DO9(Q[54]), .DO10(Q[55]), .DO11(Q[56]), 
        .DO12(Q[57]), .DO13(Q[58]), .DO14(Q[59]), .DO15(Q[60]), .DO16(Q[61]), 
        .DO17(Q[62]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_4_10.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_4_10.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_4_10.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_4_10.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_4_10.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_4_10.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_4_10.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_4_10.GSR = "DISABLED" ;
    defparam TestFifo_4_10.RESETMODE = "ASYNC" ;
    defparam TestFifo_4_10.REGMODE = "NOREG" ;
    defparam TestFifo_4_10.CSDECODE_R = "0b11" ;
    defparam TestFifo_4_10.CSDECODE_W = "0b11" ;
    defparam TestFifo_4_10.DATA_WIDTH_R = 18 ;
    defparam TestFifo_4_10.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_4_10 (.DI0(Data[72]), .DI1(Data[73]), .DI2(Data[74]), 
        .DI3(Data[75]), .DI4(Data[76]), .DI5(Data[77]), .DI6(Data[78]), 
        .DI7(Data[79]), .DI8(Data[80]), .DI9(Data[81]), .DI10(Data[82]), 
        .DI11(Data[83]), .DI12(Data[84]), .DI13(Data[85]), .DI14(Data[86]), 
        .DI15(Data[87]), .DI16(Data[88]), .DI17(Data[89]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[81]), .DO1(Q[82]), 
        .DO2(Q[83]), .DO3(Q[84]), .DO4(Q[85]), .DO5(Q[86]), .DO6(Q[87]), 
        .DO7(Q[88]), .DO8(Q[89]), .DO9(Q[72]), .DO10(Q[73]), .DO11(Q[74]), 
        .DO12(Q[75]), .DO13(Q[76]), .DO14(Q[77]), .DO15(Q[78]), .DO16(Q[79]), 
        .DO17(Q[80]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_5_9.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_5_9.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_5_9.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_5_9.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_5_9.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_5_9.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_5_9.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_5_9.GSR = "DISABLED" ;
    defparam TestFifo_5_9.RESETMODE = "ASYNC" ;
    defparam TestFifo_5_9.REGMODE = "NOREG" ;
    defparam TestFifo_5_9.CSDECODE_R = "0b11" ;
    defparam TestFifo_5_9.CSDECODE_W = "0b11" ;
    defparam TestFifo_5_9.DATA_WIDTH_R = 18 ;
    defparam TestFifo_5_9.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_5_9 (.DI0(Data[90]), .DI1(Data[91]), .DI2(Data[92]), 
        .DI3(Data[93]), .DI4(Data[94]), .DI5(Data[95]), .DI6(Data[96]), 
        .DI7(Data[97]), .DI8(Data[98]), .DI9(Data[99]), .DI10(Data[100]), 
        .DI11(Data[101]), .DI12(Data[102]), .DI13(Data[103]), .DI14(Data[104]), 
        .DI15(Data[105]), .DI16(Data[106]), .DI17(Data[107]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[99]), .DO1(Q[100]), 
        .DO2(Q[101]), .DO3(Q[102]), .DO4(Q[103]), .DO5(Q[104]), .DO6(Q[105]), 
        .DO7(Q[106]), .DO8(Q[107]), .DO9(Q[90]), .DO10(Q[91]), .DO11(Q[92]), 
        .DO12(Q[93]), .DO13(Q[94]), .DO14(Q[95]), .DO15(Q[96]), .DO16(Q[97]), 
        .DO17(Q[98]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_6_8.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_6_8.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_6_8.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_6_8.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_6_8.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_6_8.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_6_8.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_6_8.GSR = "DISABLED" ;
    defparam TestFifo_6_8.RESETMODE = "ASYNC" ;
    defparam TestFifo_6_8.REGMODE = "NOREG" ;
    defparam TestFifo_6_8.CSDECODE_R = "0b11" ;
    defparam TestFifo_6_8.CSDECODE_W = "0b11" ;
    defparam TestFifo_6_8.DATA_WIDTH_R = 18 ;
    defparam TestFifo_6_8.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_6_8 (.DI0(Data[108]), .DI1(Data[109]), .DI2(Data[110]), 
        .DI3(Data[111]), .DI4(Data[112]), .DI5(Data[113]), .DI6(Data[114]), 
        .DI7(Data[115]), .DI8(Data[116]), .DI9(Data[117]), .DI10(Data[118]), 
        .DI11(Data[119]), .DI12(Data[120]), .DI13(Data[121]), .DI14(Data[122]), 
        .DI15(Data[123]), .DI16(Data[124]), .DI17(Data[125]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[117]), .DO1(Q[118]), 
        .DO2(Q[119]), .DO3(Q[120]), .DO4(Q[121]), .DO5(Q[122]), .DO6(Q[123]), 
        .DO7(Q[124]), .DO8(Q[125]), .DO9(Q[108]), .DO10(Q[109]), .DO11(Q[110]), 
        .DO12(Q[111]), .DO13(Q[112]), .DO14(Q[113]), .DO15(Q[114]), .DO16(Q[115]), 
        .DO17(Q[116]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_7_7.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_7_7.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_7_7.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_7_7.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_7_7.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_7_7.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_7_7.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_7_7.GSR = "DISABLED" ;
    defparam TestFifo_7_7.RESETMODE = "ASYNC" ;
    defparam TestFifo_7_7.REGMODE = "NOREG" ;
    defparam TestFifo_7_7.CSDECODE_R = "0b11" ;
    defparam TestFifo_7_7.CSDECODE_W = "0b11" ;
    defparam TestFifo_7_7.DATA_WIDTH_R = 18 ;
    defparam TestFifo_7_7.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_7_7 (.DI0(Data[126]), .DI1(Data[127]), .DI2(Data[128]), 
        .DI3(Data[129]), .DI4(Data[130]), .DI5(Data[131]), .DI6(Data[132]), 
        .DI7(Data[133]), .DI8(Data[134]), .DI9(Data[135]), .DI10(Data[136]), 
        .DI11(Data[137]), .DI12(Data[138]), .DI13(Data[139]), .DI14(Data[140]), 
        .DI15(Data[141]), .DI16(Data[142]), .DI17(Data[143]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[135]), .DO1(Q[136]), 
        .DO2(Q[137]), .DO3(Q[138]), .DO4(Q[139]), .DO5(Q[140]), .DO6(Q[141]), 
        .DO7(Q[142]), .DO8(Q[143]), .DO9(Q[126]), .DO10(Q[127]), .DO11(Q[128]), 
        .DO12(Q[129]), .DO13(Q[130]), .DO14(Q[131]), .DO15(Q[132]), .DO16(Q[133]), 
        .DO17(Q[134]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_8_6.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_8_6.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_8_6.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_8_6.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_8_6.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_8_6.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_8_6.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_8_6.GSR = "DISABLED" ;
    defparam TestFifo_8_6.RESETMODE = "ASYNC" ;
    defparam TestFifo_8_6.REGMODE = "NOREG" ;
    defparam TestFifo_8_6.CSDECODE_R = "0b11" ;
    defparam TestFifo_8_6.CSDECODE_W = "0b11" ;
    defparam TestFifo_8_6.DATA_WIDTH_R = 18 ;
    defparam TestFifo_8_6.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_8_6 (.DI0(Data[144]), .DI1(Data[145]), .DI2(Data[146]), 
        .DI3(Data[147]), .DI4(Data[148]), .DI5(Data[149]), .DI6(Data[150]), 
        .DI7(Data[151]), .DI8(Data[152]), .DI9(Data[153]), .DI10(Data[154]), 
        .DI11(Data[155]), .DI12(Data[156]), .DI13(Data[157]), .DI14(Data[158]), 
        .DI15(Data[159]), .DI16(Data[160]), .DI17(Data[161]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[153]), .DO1(Q[154]), 
        .DO2(Q[155]), .DO3(Q[156]), .DO4(Q[157]), .DO5(Q[158]), .DO6(Q[159]), 
        .DO7(Q[160]), .DO8(Q[161]), .DO9(Q[144]), .DO10(Q[145]), .DO11(Q[146]), 
        .DO12(Q[147]), .DO13(Q[148]), .DO14(Q[149]), .DO15(Q[150]), .DO16(Q[151]), 
        .DO17(Q[152]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_9_5.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_9_5.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_9_5.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_9_5.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_9_5.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_9_5.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_9_5.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_9_5.GSR = "DISABLED" ;
    defparam TestFifo_9_5.RESETMODE = "ASYNC" ;
    defparam TestFifo_9_5.REGMODE = "NOREG" ;
    defparam TestFifo_9_5.CSDECODE_R = "0b11" ;
    defparam TestFifo_9_5.CSDECODE_W = "0b11" ;
    defparam TestFifo_9_5.DATA_WIDTH_R = 18 ;
    defparam TestFifo_9_5.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_9_5 (.DI0(Data[162]), .DI1(Data[163]), .DI2(Data[164]), 
        .DI3(Data[165]), .DI4(Data[166]), .DI5(Data[167]), .DI6(Data[168]), 
        .DI7(Data[169]), .DI8(Data[170]), .DI9(Data[171]), .DI10(Data[172]), 
        .DI11(Data[173]), .DI12(Data[174]), .DI13(Data[175]), .DI14(Data[176]), 
        .DI15(Data[177]), .DI16(Data[178]), .DI17(Data[179]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[171]), .DO1(Q[172]), 
        .DO2(Q[173]), .DO3(Q[174]), .DO4(Q[175]), .DO5(Q[176]), .DO6(Q[177]), 
        .DO7(Q[178]), .DO8(Q[179]), .DO9(Q[162]), .DO10(Q[163]), .DO11(Q[164]), 
        .DO12(Q[165]), .DO13(Q[166]), .DO14(Q[167]), .DO15(Q[168]), .DO16(Q[169]), 
        .DO17(Q[170]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_10_4.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_10_4.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_10_4.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_10_4.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_10_4.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_10_4.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_10_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_10_4.GSR = "DISABLED" ;
    defparam TestFifo_10_4.RESETMODE = "ASYNC" ;
    defparam TestFifo_10_4.REGMODE = "NOREG" ;
    defparam TestFifo_10_4.CSDECODE_R = "0b11" ;
    defparam TestFifo_10_4.CSDECODE_W = "0b11" ;
    defparam TestFifo_10_4.DATA_WIDTH_R = 18 ;
    defparam TestFifo_10_4.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_10_4 (.DI0(Data[180]), .DI1(Data[181]), .DI2(Data[182]), 
        .DI3(Data[183]), .DI4(Data[184]), .DI5(Data[185]), .DI6(Data[186]), 
        .DI7(Data[187]), .DI8(Data[188]), .DI9(Data[189]), .DI10(Data[190]), 
        .DI11(Data[191]), .DI12(Data[192]), .DI13(Data[193]), .DI14(Data[194]), 
        .DI15(Data[195]), .DI16(Data[196]), .DI17(Data[197]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[189]), .DO1(Q[190]), 
        .DO2(Q[191]), .DO3(Q[192]), .DO4(Q[193]), .DO5(Q[194]), .DO6(Q[195]), 
        .DO7(Q[196]), .DO8(Q[197]), .DO9(Q[180]), .DO10(Q[181]), .DO11(Q[182]), 
        .DO12(Q[183]), .DO13(Q[184]), .DO14(Q[185]), .DO15(Q[186]), .DO16(Q[187]), 
        .DO17(Q[188]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_11_3.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_11_3.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_11_3.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_11_3.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_11_3.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_11_3.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_11_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_11_3.GSR = "DISABLED" ;
    defparam TestFifo_11_3.RESETMODE = "ASYNC" ;
    defparam TestFifo_11_3.REGMODE = "NOREG" ;
    defparam TestFifo_11_3.CSDECODE_R = "0b11" ;
    defparam TestFifo_11_3.CSDECODE_W = "0b11" ;
    defparam TestFifo_11_3.DATA_WIDTH_R = 18 ;
    defparam TestFifo_11_3.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_11_3 (.DI0(Data[198]), .DI1(Data[199]), .DI2(Data[200]), 
        .DI3(Data[201]), .DI4(Data[202]), .DI5(Data[203]), .DI6(Data[204]), 
        .DI7(Data[205]), .DI8(Data[206]), .DI9(Data[207]), .DI10(Data[208]), 
        .DI11(Data[209]), .DI12(Data[210]), .DI13(Data[211]), .DI14(Data[212]), 
        .DI15(Data[213]), .DI16(Data[214]), .DI17(Data[215]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[207]), .DO1(Q[208]), 
        .DO2(Q[209]), .DO3(Q[210]), .DO4(Q[211]), .DO5(Q[212]), .DO6(Q[213]), 
        .DO7(Q[214]), .DO8(Q[215]), .DO9(Q[198]), .DO10(Q[199]), .DO11(Q[200]), 
        .DO12(Q[201]), .DO13(Q[202]), .DO14(Q[203]), .DO15(Q[204]), .DO16(Q[205]), 
        .DO17(Q[206]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_12_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_12_2.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_12_2.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_12_2.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_12_2.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_12_2.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_12_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_12_2.GSR = "DISABLED" ;
    defparam TestFifo_12_2.RESETMODE = "ASYNC" ;
    defparam TestFifo_12_2.REGMODE = "NOREG" ;
    defparam TestFifo_12_2.CSDECODE_R = "0b11" ;
    defparam TestFifo_12_2.CSDECODE_W = "0b11" ;
    defparam TestFifo_12_2.DATA_WIDTH_R = 18 ;
    defparam TestFifo_12_2.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_12_2 (.DI0(Data[216]), .DI1(Data[217]), .DI2(Data[218]), 
        .DI3(Data[219]), .DI4(Data[220]), .DI5(Data[221]), .DI6(Data[222]), 
        .DI7(Data[223]), .DI8(Data[224]), .DI9(Data[225]), .DI10(Data[226]), 
        .DI11(Data[227]), .DI12(Data[228]), .DI13(Data[229]), .DI14(Data[230]), 
        .DI15(Data[231]), .DI16(Data[232]), .DI17(Data[233]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[225]), .DO1(Q[226]), 
        .DO2(Q[227]), .DO3(Q[228]), .DO4(Q[229]), .DO5(Q[230]), .DO6(Q[231]), 
        .DO7(Q[232]), .DO8(Q[233]), .DO9(Q[216]), .DO10(Q[217]), .DO11(Q[218]), 
        .DO12(Q[219]), .DO13(Q[220]), .DO14(Q[221]), .DO15(Q[222]), .DO16(Q[223]), 
        .DO17(Q[224]), .EF(), .AEF(), .AFF(), .FF());

    defparam TestFifo_13_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_13_1.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_13_1.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_13_1.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_13_1.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_13_1.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_13_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_13_1.GSR = "DISABLED" ;
    defparam TestFifo_13_1.RESETMODE = "ASYNC" ;
    defparam TestFifo_13_1.REGMODE = "NOREG" ;
    defparam TestFifo_13_1.CSDECODE_R = "0b11" ;
    defparam TestFifo_13_1.CSDECODE_W = "0b11" ;
    defparam TestFifo_13_1.DATA_WIDTH_R = 18 ;
    defparam TestFifo_13_1.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_13_1 (.DI0(Data[234]), .DI1(Data[235]), .DI2(Data[236]), 
        .DI3(Data[237]), .DI4(Data[238]), .DI5(Data[239]), .DI6(Data[240]), 
        .DI7(Data[241]), .DI8(Data[242]), .DI9(Data[243]), .DI10(Data[244]), 
        .DI11(Data[245]), .DI12(Data[246]), .DI13(Data[247]), .DI14(Data[248]), 
        .DI15(Data[249]), .DI16(Data[250]), .DI17(Data[251]), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[243]), .DO1(Q[244]), 
        .DO2(Q[245]), .DO3(Q[246]), .DO4(Q[247]), .DO5(Q[248]), .DO6(Q[249]), 
        .DO7(Q[250]), .DO8(Q[251]), .DO9(Q[234]), .DO10(Q[235]), .DO11(Q[236]), 
        .DO12(Q[237]), .DO13(Q[238]), .DO14(Q[239]), .DO15(Q[240]), .DO16(Q[241]), 
        .DO17(Q[242]), .EF(), .AEF(), .AFF(), .FF());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam TestFifo_14_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_14_0.FULLPOINTER = "0b11111111110000" ;
    defparam TestFifo_14_0.AFPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_14_0.AFPOINTER = "0b11111111110000" ;
    defparam TestFifo_14_0.AEPOINTER1 = "0b00000000000000" ;
    defparam TestFifo_14_0.AEPOINTER = "0b11111111110000" ;
    defparam TestFifo_14_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam TestFifo_14_0.GSR = "DISABLED" ;
    defparam TestFifo_14_0.RESETMODE = "ASYNC" ;
    defparam TestFifo_14_0.REGMODE = "NOREG" ;
    defparam TestFifo_14_0.CSDECODE_R = "0b11" ;
    defparam TestFifo_14_0.CSDECODE_W = "0b11" ;
    defparam TestFifo_14_0.DATA_WIDTH_R = 18 ;
    defparam TestFifo_14_0.DATA_WIDTH_W = 18 ;
    FIFO8KB TestFifo_14_0 (.DI0(Data[252]), .DI1(Data[253]), .DI2(Data[254]), 
        .DI3(Data[255]), .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(scuba_vlo), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(), .DO1(), .DO2(), 
        .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(Q[252]), .DO10(Q[253]), 
        .DO11(Q[254]), .DO12(Q[255]), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
